version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: codeclimate-test-reporter
    versions:
    - "> 0.4.1"
  - dependency-name: json_pure
    versions:
    - "< 3, >= 2.a"
  - dependency-name: mime-types
    versions:
    - "> 1.25.1"
  - dependency-name: rubocop
    versions:
    - "> 0.49.1"
