inherit_from: .rubocop_cocoapods.yml

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/resolver_integration_specs/**/*'

Style/TrailingComma:
  Enabled: false

RaiseArgs:
  Enabled: false

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/molinillo/modules/**/*'

# CocoaPods default overrides

Metrics/CyclomaticComplexity:
  Enabled: true
